feat: Updated result styles
trybick/issue-collab pull request #11
Opened 2019-10-07 02:22 UTC by jmoranin98

#2 
![screenshot](https://user-images.githubusercontent.com/33536607/66281092-5d944700-e87f-11e9-9c13-46bc5978c5af.png)

2019-10-07 08:10 UTC, lemieszek requested changes
there is other file with a `result` class. Do not make spaghetti

2019-10-07 08:10 UTC, d-szymanski commented on src/styles/Results.scss
> +@import url('https://fonts.googleapis.com/css?family=Lato|Roboto+Mono&display=swap');
import fonts globally

2019-10-07 08:10 UTC, d-szymanski commented on src/styles/Results.scss
> +.result {
yet another file with `.result` class :(

2019-10-07 08:10 UTC, d-szymanski commented on src/components/core/Chip.jsx
> +const Chip = ({ text, color }) => {
👏  great!

2019-10-08 00:15 UTC, merged

2019-10-08 00:16 UTC, trybick commented
@jmoranin98 Thank you! Looks amazing.

@d-szymanski Thanks for the tips

🚀